# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FileTree(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, dir: List[str]=None):  # noqa: E501
        """FileTree - a model defined in Swagger

        :param dir: The dir of this FileTree.  # noqa: E501
        :type dir: List[str]
        """
        self.swagger_types = {
            'dir': List[str]
        }

        self.attribute_map = {
            'dir': 'dir'
        }
        self._dir = dir

    @classmethod
    def from_dict(cls, dikt) -> 'FileTree':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FileTree of this FileTree.  # noqa: E501
        :rtype: FileTree
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dir(self) -> List[str]:
        """Gets the dir of this FileTree.


        :return: The dir of this FileTree.
        :rtype: List[str]
        """
        return self._dir

    @dir.setter
    def dir(self, dir: List[str]):
        """Sets the dir of this FileTree.


        :param dir: The dir of this FileTree.
        :type dir: List[str]
        """
        if dir is None:
            raise ValueError("Invalid value for `dir`, must not be `None`")  # noqa: E501

        self._dir = dir
