# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Point(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, x: int=None, y: int=None):  # noqa: E501
        """Point - a model defined in Swagger

        :param id: The id of this Point.  # noqa: E501
        :type id: int
        :param x: The x of this Point.  # noqa: E501
        :type x: int
        :param y: The y of this Point.  # noqa: E501
        :type y: int
        """
        self.swagger_types = {
            'id': int,
            'x': int,
            'y': int
        }

        self.attribute_map = {
            'id': 'id',
            'x': 'x',
            'y': 'y'
        }
        self._id = id
        self._x = x
        self._y = y

    @classmethod
    def from_dict(cls, dikt) -> 'Point':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Point of this Point.  # noqa: E501
        :rtype: Point
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Point.


        :return: The id of this Point.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Point.


        :param id: The id of this Point.
        :type id: int
        """

        self._id = id

    @property
    def x(self) -> int:
        """Gets the x of this Point.


        :return: The x of this Point.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x: int):
        """Sets the x of this Point.


        :param x: The x of this Point.
        :type x: int
        """

        self._x = x

    @property
    def y(self) -> int:
        """Gets the y of this Point.


        :return: The y of this Point.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y: int):
        """Sets the y of this Point.


        :param y: The y of this Point.
        :type y: int
        """

        self._y = y
